--local opts = {
--	prompt = "PROMPT => ",
--	--default = "there was a default"
--}
--local on_confirm = function(input)
--	print("on_confirm")
--	print(vim.inspect(input))
--	return true
--end
--
----local result = vim.ui.input(opts, on_confirm)
----print("result")
----print(vim.inspect(result))
--
--vim.api.nvim_echo({{'first chunk and ', 'Error'}, {'second chunk to echo', 'None'}}, false, {})

